In [1]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import StandardScaler
import torch

# Adult

In [65]:
adult_train = pd.read_csv("adult.data", 
                          index_col=False,
                          names=["age", 
                                "workclass",
                                "fnlwgt", 
                                "education", 
                                "education-num", 
                                "marital-status", 
                                "occupation", 
                                "relationship", 
                                "race", 
                                "sex", 
                                "capital-gain", 
                                "capital-loss", 
                                "hours-per-week", 
                                "native-country", 
                                "income"])

In [66]:
# Removed [fnlwgt, educational-num]
adult_train = adult_train[["workclass",
                        "education", 
                        "marital-status", 
                        "occupation", 
                        "relationship", 
                        "race", 
                        "sex", 
                        "native-country", 
                        "capital-gain", 
                        "capital-loss", 
                        "hours-per-week",
                        "age",  
                        "income"]]
adult_train.head()

,workclass,education,marital-status,occupation,relationship,race,sex,native-country,capital-gain,capital-loss,hours-per-week,age,income
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States,2174,0,40,39,<=50K
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,0,0,13,50,<=50K
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States,0,0,40,38,<=50K
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States,0,0,40,53,<=50K
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba,0,0,40,28,<=50K

In [67]:
std_scaler = StandardScaler()
df_scaled = std_scaler.fit_transform(a[["capital-gain", "capital-loss"]].to_numpy().reshape(-1, 2))
# std_scaler.inverse_transform(df_scaled)

In [70]:
pd.DataFrame(df_scaled, columns=["capital-gain", "capital-loss"])

       capital-gain  capital-loss
0          0.148453      -0.21666
1         -0.145920      -0.21666
2         -0.145920      -0.21666
3         -0.145920      -0.21666
4         -0.145920      -0.21666
...             ...           ...
32556     -0.145920      -0.21666
32557     -0.145920      -0.21666
32558     -0.145920      -0.21666
32559     -0.145920      -0.21666
32560      1.888424      -0.21666

[32561 rows x 2 columns]

In [71]:
adult_train[["capital-gain", "capital-loss"]] = pd.DataFrame(df_scaled, columns=["capital-gain", "capital-loss"])

In [82]:
torch.Tensor(adult_train.values)

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

# Mushroom

In [50]:
mushroom = pd.read_csv("agaricus-lepiota.data", 
                       index_col=False,
                       names=["poison", 
                              "cap-shape", 
                              "cap-surface", 
                              "cap-color", 
                              "bruises", 
                              "odor", 
                              "gill-attachment", 
                              "gill-spacing", 
                              "gill-size", 
                              "gill-color", 
                              "stalk-shape", 
                              "stalk-root", 
                              "stalk-surface-above-ring", 
                              "stalk-surface-below-ring", 
                              "stalk-color-above-ring", 
                              "stalk-color-below-ring", 
                              "veil-type", 
                              "veil-color", 
                              "ring-number", 
                              "ring-type", 
                              "spore-print-color", 
                              "population", 
                              "habitat"])
mushroom = mushroom[["cap-shape", 
                    "cap-surface", 
                    "cap-color", 
                    "bruises", 
                    "odor", 
                    "gill-attachment", 
                    "gill-spacing", 
                    "gill-size", 
                    "gill-color", 
                    "stalk-shape", 
                    "stalk-root", 
                    "stalk-surface-above-ring", 
                    "stalk-surface-below-ring", 
                    "stalk-color-above-ring", 
                    "stalk-color-below-ring", 
                    "veil-type", 
                    "veil-color", 
                    "ring-number", 
                    "ring-type", 
                    "spore-print-color", 
                    "population", 
                    "habitat", 
                    "poison"]]
mushroom.drop(mushroom[mushroom['stalk-root'] == '?'].index, inplace = True)  # 2480 rows
mushroom

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,poison
0,x,s,n,t,p,f,c,n,k,e,...,w,w,p,w,o,p,k,s,u,p
1,x,s,y,t,a,f,c,b,k,e,...,w,w,p,w,o,p,n,n,g,e
2,b,s,w,t,l,f,c,b,n,e,...,w,w,p,w,o,p,n,n,m,e
3,x,y,w,t,p,f,c,n,n,e,...,w,w,p,w,o,p,k,s,u,p
4,x,s,g,f,n,f,w,b,k,t,...,w,w,p,w,o,e,n,a,g,e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,b,y,n,f,n,f,c,b,w,e,...,n,n,p,w,t,p,w,y,p,e
8001,x,y,n,f,n,f,c,b,w,e,...,n,n,p,w,t,p,w,y,p,e
8038,x,y,g,t,n,f,c,b,w,e,...,w,w,p,w,t,p,w,y,p,e
8095,x,y,c,f,m,f,c,b,y,e,...,c,c,p,w,n,n,w,c,d,p
8114,f,y,c,f,m,a,c,b,y,e,...,c,c,p,w,n,n,w,c,d,p

In [49]:
np.unique(mushroom["stalk-root"])

array(['?', 'b', 'c', 'e', 'r'], dtype=object)

# Obesity

In [64]:
obesity = pd.read_csv("ObesityDataSet_raw_and_data_sinthetic.csv")
obesity = obesity[['Age', 
                   'Height', 
                   'Weight', 
                   'FCVC',
                   'NCP',
                   'CH2O', 
                   'FAF', 
                   'TUE', 

                   'Gender', 
                   'family_history_with_overweight', 
                   'FAVC', 
                   'CAEC', 
                   'SMOKE',                     
                   'SCC', 
                   'CALC', 
                   'MTRANS', 
                   'NObeyesdad']]
obesity

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,Gender,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS,NObeyesdad
0,21.000000,1.620000,64.000000,2.0,3.0,2.000000,0.000000,1.000000,Female,yes,no,Sometimes,no,no,no,Public_Transportation,Normal_Weight
1,21.000000,1.520000,56.000000,3.0,3.0,3.000000,3.000000,0.000000,Female,yes,no,Sometimes,yes,yes,Sometimes,Public_Transportation,Normal_Weight
2,23.000000,1.800000,77.000000,2.0,3.0,2.000000,2.000000,1.000000,Male,yes,no,Sometimes,no,no,Frequently,Public_Transportation,Normal_Weight
3,27.000000,1.800000,87.000000,3.0,3.0,2.000000,2.000000,0.000000,Male,no,no,Sometimes,no,no,Frequently,Walking,Overweight_Level_I
4,22.000000,1.780000,89.800000,2.0,1.0,2.000000,0.000000,0.000000,Male,no,no,Sometimes,no,no,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,1.710730,131.408528,3.0,3.0,1.728139,1.676269,0.906247,Female,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,1.748584,133.742943,3.0,3.0,2.005130,1.341390,0.599270,Female,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,1.752206,133.689352,3.0,3.0,2.054193,1.414209,0.646288,Female,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,1.739450,133.346641,3.0,3.0,2.852339,1.139107,0.586035,Female,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,1.738836,133.472641,3.0,3.0,2.863513,1.026452,0.714137,Female,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III

# Others

In [85]:
a = torch.Tensor([1, 2, 3]).reshape(-1, 1)
b = torch.Tensor([1, 2, 3]).reshape(-1, 1)
torch.cat([a, b], 1)

tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])

In [7]:
a = torch.nn.Linear(3, 0)(torch.Tensor([1, 2, 3]))
b = torch.nn.Linear(3, 2)(torch.Tensor([1, 2, 3]))
torch.cat([a, b])

tensor([-0.8270,  1.9271], grad_fn=<CatBackward0>)